<?php

namespace OdaliBundle\Repository;

/**
 * categoria_ticketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoria_ticketRepository extends \Doctrine\ORM\EntityRepository
{
}
