<?php

namespace OdaliBundle\Repository;

/**
 * departamento_proyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class departamento_proyectoRepository extends \Doctrine\ORM\EntityRepository
{
}
