<?php

namespace OdaliBundle\Repository;

/**
 * historial_ticketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class historial_ticketRepository extends \Doctrine\ORM\EntityRepository
{
}
