<?php

namespace OdaliBundle\Repository;

/**
 * notasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notasRepository extends \Doctrine\ORM\EntityRepository
{
}
