<?php

namespace OdaliBundle\Repository;

/**
 * rolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rolesRepository extends \Doctrine\ORM\EntityRepository
{
}
