<?php

namespace OdaliBundle\Repository;

/**
 * usuario_categoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuario_categoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
